# docker-compose.ymlファイルのバージョンを指定します。使用する機能によって異なります。
version: "3.7"

# 'services' キーの下に、管理するサービス（コンテナ）を列挙します。
services:
  # 'app' はここで定義するサービス（コンテナ）の名前です。
  app:
    # 現在のディレクトリにあるDockerfileを使用して、コンテナのイメージをビルドします。
    build: ./
    platform: linux/amd64

    # コンテナが起動したら実行されるコマンド。ここでは開発サーバーを起動します。
    # command: npm run dev

    # ボリュームのマウント設定。ホストマシンの現在のディレクトリをコンテナの '/root' ディレクトリにマウントします。
    # これにより、ホストマシン上のファイルの変更がコンテナにリアルタイムで反映されます。
    volumes:
      - ./:/root

    # ホストとコンテナのポートマッピング設定。
    # ホストマシンのポート3000をコンテナ内のポート3000にマッピングします。
    ports:
      - 3000:3000

    # コンテナに仮想ターミナル（tty）を割り当てます。これは、コンテナをバックグラウンドではなくフォアグラウンドで実行するために使用されます。
    tty: true

    # ECRのリポジトリのイメージ
    image: 905418423138.dkr.ecr.ap-northeast-1.amazonaws.com/mensetsu-repo:1.0.0
